enum TokenType {
    TOKEN_EOF,
    TOKEN_RAW,
    TOKEN_RAW_BEGIN,
    TOKEN_RAW_END,
    TOKEN_COMP_BEGIN,
    TOKEN_COMP_END,
    TOKEN_COMMA,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_ID,
    TOKEN_EQUALS,
    TOKEN_STRING,
    TOKEN_NUMBER,
    TOKEN_COMMENT,
    TOKEN_DOT,
    TOKEN_ARROW_RIGHT,
}

export default TokenType